apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  
  labels:
    app: zabbix-web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
  externalIPs:
    - 20.119.193.135  
  selector:
    app: zabbix-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
  
  labels:
    app: zabbix-web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
      tier: frontend
  template:
    metadata:
      labels:
        app: zabbix-web
        tier: frontend
    spec:
      containers:
      - image: zabbix/zabbix-web-apache-mysql:alpine-5.4.7
        name: zabbix-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web 
          protocol: TCP
        env:
          - name: ZBX_SERVER_NAME
            value: "Zabbix Rede Dor"
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: DB_SERVER_HOST
            value: "mysql-master-db"
          - name: DB_SERVER_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "zabbix"
          - name: MYSQL_USER
            value: zabbix
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-pwd
                key: mysql-master-root-pwd
          - name: PHP_TZ
            value: America/Sao_Paulo
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            cpu: 500m
            memory: 750Mi   
