apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQyakNDQXNJQ0NRQ3ZQT05B
    ZWZJMGNEQU5CZ2txaGtpRzl3MEJBUXNGQURDQnJqRUxNQWtHQTFVRUJoTUMKVTFB
    eEZUQVRCZ05WQkFnTURGUERnOEtqYnlCUVlYVnNiekVWTUJNR0ExVUVCd3dNVThP
    RHdxTnZJRkJoZFd4dgpNUkV3RHdZRFZRUUtEQWhTWldSbElFUnZjakVSTUE4R0Ex
    VUVDd3dJVW1Wa1pTQmtiM0l4RnpBVkJnTlZCQU1NCkRteGhZbWR5WVdaaGJtRXVZ
    Mjl0TVRJd01BWUpLb1pJaHZjTkFRa0JGaU5xYjJGdkxuWnBiR0Z1YVhKdFpXeHYK
    UUdWMlpYSnBjeTV1ZEhSa1lYUmhMbU52YlRBZUZ3MHlNVEV4TVRBeE9USTBNakJh
    Rncwek1URXhNRGd4T1RJMApNakJhTUlHdU1Rc3dDUVlEVlFRR0V3SlRVREVWTUJN
    R0ExVUVDQXdNVThPRHdxTnZJRkJoZFd4dk1SVXdFd1lEClZRUUhEQXhUdzRQQ28y
    OGdVR0YxYkc4eEVUQVBCZ05WQkFvTUNGSmxaR1VnUkc5eU1SRXdEd1lEVlFRTERB
    aFMKWldSbElHUnZjakVYTUJVR0ExVUVBd3dPYkdGaVozSmhabUZ1WVM1amIyMHhN
    akF3QmdrcWhraUc5dzBCQ1FFVwpJMnB2WVc4dWRtbHNZVzVwY20xbGJHOUFaWFps
    Y21sekxtNTBkR1JoZEdFdVkyOXRNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFP
    Q0FROEFNSUlCQ2dLQ0FRRUF2b1VoVHAwUjZYODJTT1BRR3R5WFJ3elNqUlcrUWFU
    TVQyUXkKbVNzWXE3MEdsV1dUZjdFQU91Zjg2b2ZTWEhTQ1hIVmlkWnh1NUdkQkFT
    dW94RkpJYzZ1a2c3RlJLMHlkOGk4Qwpwa2ZoM3pzOWo4UkFDKzdURldEby9oMGs3
    VWUvNDU0Vm14SWNYc3RXWjQyVlRSUVV2WUFkUTd2cmxnMW10bEFNCmZPV3lkdDZF
    d1hsUE1EZHNLdjZtZ3lDZGFQWk45cjE2dm4vUk52NjBkRmFqU1FvU0xxMHhFeWNs
    ZGt6MUNZQXAKQThUZUlTbGozcEFnNWNuMGlyY0ZLUGVCTlQxcm9oV1JHOFY3NmRD
    a29oU3lFYzNVV3VWTGZQZWY0NXdkcHhjVwpHYVVJWllVbVNBTXpXRmp0ZXY2cVZP
    ZXcycC9kZVVQTWExa0VKZHJybkY1NEdNckY5d0lEQVFBQk1BMEdDU3FHClNJYjNE
    UUVCQ3dVQUE0SUJBUUM1WkkxcUgxaEdCclk4T3FzcFd5Q1FyRDBlWFkrbUt6YmJs
    Rk1OVjZhMlNQa3YKUmN3SDY3ajZIaXh3VGc0WlJ1K0NKTXFrOVpHaUNNcGxaOEpE
    ekVubGMrWVJidlVNUllhWGZqRVdrVEt4aVkyRwpXeWl0NGVMaU1Hb3dCOThvZTI3
    ZGhBdEloRnJPS1Q2SW93S1o4YWg0MFZBOURHN2E0Ny82ZFVHQURHOERIaWkzCnNC
    UG5WaGVaZUZIVVA0RVFGWW9iRHM1b2pIRXY1OGl6ZURwaFNvbFdKdG1Ldy9yb2hG
    SDNlTDM4ZjZYZlBoUkYKSHFWaE8zNWlvT1pDbmMvM1RocmpBQWI1TUZyZkg4VzNr
    eEFMQUJmaDlHYmp5V2NVL21HZkxMbzU4eXZjOUNrMApVRmFveUY5QXAvNzBRdm1P
    d1NHazlia2daa1JXaU9wRVJXSnJDaUI2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
    LS0K

  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVB
    dm9VaFRwMFI2WDgyU09QUUd0eVhSd3pTalJXK1FhVE1UMlF5bVNzWXE3MEdsV1dU
    CmY3RUFPdWY4Nm9mU1hIU0NYSFZpZFp4dTVHZEJBU3VveEZKSWM2dWtnN0ZSSzB5
    ZDhpOENwa2ZoM3pzOWo4UkEKQys3VEZXRG8vaDBrN1VlLzQ1NFZteEljWHN0V1o0
    MlZUUlFVdllBZFE3dnJsZzFtdGxBTWZPV3lkdDZFd1hsUApNRGRzS3Y2bWd5Q2Rh
    UFpOOXIxNnZuL1JOdjYwZEZhalNRb1NMcTB4RXljbGRrejFDWUFwQThUZUlTbGoz
    cEFnCjVjbjBpcmNGS1BlQk5UMXJvaFdSRzhWNzZkQ2tvaFN5RWMzVVd1VkxmUGVm
    NDV3ZHB4Y1dHYVVJWllVbVNBTXoKV0ZqdGV2NnFWT2V3MnAvZGVVUE1hMWtFSmRy
    cm5GNTRHTXJGOXdJREFRQUJBb0lCQUF6L1dobFozOW4xSXNmdwpPc2RLVzB1dWxV
    S294QlVJWUNQZWF4RkYvbVhnL0d6K3hBUkhHQVBzeGJWZVZMeVgrampDalZnR3R3
    My8rVkJTCklTNWJpclBSZHVUQkdRK0NKNWhaR3E0cll6NXVkVEcwcXNYbG9pTG9Q
    Snp4Y2c1NkFaNU9yNXlucktYTzYzTWYKRnB0dWprZXJVTlBKSXpaV2JiWnNXWjIv
    c2VBb0NjTTVLZGtLcmFxbkxhejBHTU5ZZXFnRnV2ZUpiYStKOW9Ucgp5N2FWbkdU
    ZGc4U080ZDJ4cmFEMmxncXhxOFFmUTFWRHBKQXAzQStQbUFMc3VvVHczNldrRGI5
    T2NVa1NXejU0Ck9yUHNjTVgrdkhGTXZUaTdBTEdrem5LUkxlU3QxOUYzMjM5UFgw
    Y0VydUdxaTVKSWRFQzd2TVdGZGJscXhJdjYKRURKOFBLa0NnWUVBOTh5dkNnekhW
    MFEwMk4zTjZhb2VvRnpuM3RONDF6cDJrK2VmWTlSdXZ5ckRabDdxU2lrZgo3MDhP
    bEptbVJ2MWtWbytzQU9lZmNDcWNzVldlcTVqdmhVQ2IzYU94NnhsNGZINzBGRUcv
    bFhhQzA4UWhZVUNHCm5ZcGFrSnp0eGN2ckp1RkF5ckZuZTlMV1JSKzFoc0VCSmRR
    Tkt5OHZvaEk0QXUySDZpaHBFak1DZ1lFQXhOTXYKR04zSU45MzZ2VzhyamREQUZu
    ZjVEV05OcldDVTFjY0xKdEFXRmg5MW92YUJVQk1WMEgrOTlpTkFMS2JqZkxPcQps
    emIvdTR4RXVRY2ZmbXo4bmdqYmVhemJlZkJCN0RLN1VVQUxPblZWR2YwaW1NcVVQ
    cjUyRnNsS2dFWmRHcU5xCkFTMXpDc3lpSVorZEtuUVdBeG03MXdyb0dGWHByb1lK
    R21zZUlTMENnWUI0QU4zNzVmaGJvS0pmSy90ZVg0NTUKWnNTN3Vublk4VzBmYjVw
    WEJEZWx5SlhjYTdiV3QxZkowdVZpdlk0eTd0KzZzOVUra3UwNXFzazdjQlZwVUtV
    ZQpTUTJ5cG1XeFR5SjBXQjduK0hkSmNKMG01T0t0Y0V4QTJ4SEUydHFqWVgrOTBu
    UklOT1hDcDNZdy80d3ZlQ1NRCkowTkJXSmFlekdmbnN4U1JKNFRLMVFLQmdRQ0lT
    b2d4V3RuYXZhNXo0SGd6VWxyQTlFQ1VJYkJYSHlyUXdXeWEKYXJyd2hNWkxteEEr
    SjRrU2dISkU3M0h2dVh5TERFcFRQWFZtSkNJdVVaMWdTUTNBVFBmVlVIb0YvUFZa
    SG1RUgpSaHpBVlNFaHh1UmZFdUFHZHBLRkFzdkErWGhkQ3MxTGxYSTFCekE1d2pI
    dGhNYjlUS09DcS8yOVpEaFZibUQ5ClZ6RmMzUUtCZ0RPeE5oSGhrQkw3eFAzRzYy
    WXlRZ1JuSFVZR1hreVZPRzJVeEE0WUtLdHBVbHhvNFVGUkF6ZEgKUWJ6bmErYjF1
    M1hIbFdoa1VnRFgwOGFQdTVxakk5NkdUQjJ0ZXhBRHd2RUpLNmQyUkpTS0JUOE90
    R25oZWFQbwpYSjRPd0pQenMxSXFjS05TY1hyRmpQQkcvZEdCMUhCL1RJVVFENzlp
    VFlneW5VanVPWThOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==