apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
data:
  my.sh: |
    serverid=$(cat /proc/sys/kernel/random/uuid | awk -F- '{printf $1}' | sed 's/[a-zA-Z]//g')
    
    cat > /etc/mysql/my.cnf <<EOF
    [mysqld]
    default_storage_engine = innodb
    default_authentication_plugin = mysql_native_password
    pid-file         = /var/run/mysqld/mysqld.pid
    socket           = /var/lib/mysqld/mysqld.sock
    datadir          = /var/lib/mysql
    log-bin          = /var/lib/mysql/mysql-bin.log
    socket           = /var/lib/mysql/mysql.sock
    tmpdir           = /tmp
                
    secure-file-priv = NULL
    symbolic-links   = 0
    bind-address     = 0.0.0.0
    binlog_format = ROW
    sync_binlog = 1
    slow_query_log
    innodb_log_file_size = 256M
    innodb_flush_log_at_trx_commit = 2
    innodb_doublewrite = 0
    innodb_flush_method = fsync
    innodb_buffer_pool_size = 11G
    innodb_io_capacity = 8192
    innodb_read_io_threads = 64
    innodb_thread_concurrency = 0
    innodb_write_io_threads = 64
    innodb_buffer_pool_instances = 8
    innodb_lru_scan_depth = 8192
    max_connections = 1000
    innodb_buffer_pool_size=8G    
    # Custom config should go here
    !includedir /etc/mysql/conf.d/
    EOF
    echo "server-id = $serverid" >> /etc/mysql/my.cnf
    /etc/mysql/master.sh &
  master.sh: |
    sleep 10
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "SET GLOBAL server_id = $serverid;"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "CREATE USER slave@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "GRANT REPLICATION SLAVE ON *.* TO 'slave'@'%';"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "FLUSH PRIVILEGES;"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "FLUSH TABLES WITH READ LOCK;"
