apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
  
data:
  my.sh: |
    serverid=$(cat /proc/sys/kernel/random/uuid | awk -F- '{printf $1}' | sed 's/[a-zA-Z]//g')
    cat > /etc/mysql/my.cnf <<EOF
    [mysqld]
    default_storage_engine = innodb
    default_authentication_plugin = mysql_native_password
    pid-file         = /var/run/mysqld/mysqld.pid
    socket           = /var/lib/mysqld/mysqld.sock
    datadir          = /var/lib/mysql
    log-bin          = /var/lib/mysql/mysql-bin.log
    socket           = /var/lib/mysql/mysql.sock
    tmpdir           = /tmp
    read-only  = 1      
    secure-file-priv = NULL
    symbolic-links   = 0
    bind-address     = 0.0.0.0
    binlog_format    = ROW
    sync_binlog      = 1
    slow_query_log
    innodb_log_file_size = 256M
    innodb_flush_log_at_trx_commit = 2
    innodb_doublewrite = 0
    innodb_flush_method = fsync
    innodb_buffer_pool_size = 11G
    innodb_io_capacity = 8192
    innodb_read_io_threads = 64
    innodb_thread_concurrency = 0
    innodb_write_io_threads = 64
    innodb_buffer_pool_instances = 8
    innodb_lru_scan_depth = 8192
    max_connections = 1000
    innodb_buffer_pool_size=8G    

    # Custom config should go here
    !includedir /etc/mysql/conf.d/
    EOF
    echo "server-id = $serverid" >> /etc/mysql/my.cnf
    /etc/mysql/slave.sh &
  slave.sh: |
    sleep 15
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "STOP SLAVE;"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "RESET SLAVE;"
    mysqldump -h mysql-master-db -uroot -p$MYSQL_ROOT_PASSWORD --all-databases --set-gtid-purged=off > /etc/mysql/dump.sql
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock < /etc/mysql/dump.sql
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "UNLOCK TABLES;"
    MASTER_LOG_FILE=$(mysql -hmysql-master-db -uroot -p$MYSQL_ROOT_PASSWORD -e "show master status;" | grep bin  | awk -F" " '{printf $1}'| awk NR==01)
    MASTER_LOG_POS=$(mysql -hmysql-master-db -uroot -p$MYSQL_ROOT_PASSWORD -e "show master status;" | grep bin  | awk -F" " '{printf $2}'| awk NR==01)
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "CHANGE MASTER TO MASTER_HOST='mysql-master-db',MASTER_USER='slave', MASTER_PASSWORD='$MYSQL_ROOT_PASSWORD', MASTER_LOG_FILE='$MASTER_LOG_FILE', MASTER_LOG_POS=$MASTER_LOG_POS;"
    mysql -uroot -p$MYSQL_ROOT_PASSWORD -S /var/lib/mysql/mysql.sock -e "START SLAVE;"
