- hosts: all
  become: yes
  tasks:
   - name: Adionar repositorio Docker
     shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

   - name: Instalando docker
     yum:
      name: "{{ packages }}"
     vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

   - name: Iniciar docker
     service:
      name: docker
      enabled: yes
      state: started
  
   - name: Habilitar o docker
     shell: systemctl enable docker.service

   - name: Definir valor do net.bridge.bridge-nf-call-ip6tables para 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: Definir valor do net.bridge.bridge-nf-call-iptables para 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: Adionar repositorio Kubernetes
     yum_repository:
      name: Kubernetes
      description: Repositorio yum Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: Instalando kubelet
     yum:
        name: kubelet
        state: present
        update_cache: true
    
   - name: Instalando kubeadm
     yum:
        name: kubeadm
        state: present

   - name: Configurar cgroup-Driver do kubelet
     shell: cgroup=$(docker info | grep "Cgroup Driver" | awk -F" " '{printf $3}') && echo "KUBELET_EXTRA_ARGS=--cgroup-driver=$cgroup" > /etc/sysconfig/kubelet

   - name: Config Registry
     shell: echo "ewogICJpbnNlY3VyZS1yZWdpc3RyaWVzIiA6IFsibmV4dXMzLnVtYW5lcGxhdGZvcm0uY29tOjgwODIiLCJuZXh1czMudW1hbmVwbGF0Zm9ybS5jb206ODA4MyJdCn0K" |base64 -i --decode > /etc/docker/daemon.json
  
   - name: Iniciar kubelet
     service:
      name: kubelet
      enabled: yes
      state: started

   - name: Install git
     yum:
      name: git
      state: present
      update_cache: yes

    #Desabilitando o SElinux
   - name: Desabilitando SElinux
     command: setenforce 0
     register: command_result
     failed_when: "'FAILED' in command_result.stderr"

- hosts: master
  become: yes
  tasks:
    - name: instalando kubectl no master
      yum:
        name: kubectl
        state: present
