- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Criar token
      become_user: ansible
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Setar o valor do token em uma variavel
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Reset kubeadm
      shell: kubeadm reset -f

    - name: Limpeza de links
      shell: ip link set cni0 down && ip link set flannel.1 down && ip link delete cni0 && ip link delete flannel.1
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
    
    - name: Vincular Nodes ao Cluster
      shell: "{{ hostvars['master'].join_command }}" 

    - name: Criar diretorio dos volumes grafana
      become: yes
      file:
        path: /opt/Monitor_ITOC/grafana
        state: directory
        mode: 0755
        owner: ansible
        group: ansible

    - name: Criar diretorio dos volumes mysql
      become: yes
      file:
        path: /opt/Monitor_ITOC/mysql
        state: directory
        mode: 0755
        owner: ansible
        group: ansible